public class B2CRowWrapper {
    public String name;
    public String email;
    public String phone;
    public String program;
    public String country;
    public String state;
    public String city;
    public String workExp;
    public String examScoreFlag;
    public String examName;
    public String partnerCompany;
    public String organization;
    public String source;
    public String designation;
    public String age;
    public String college;
    public String graduationYear;
}